name: bitacora_web
description: "BitFlow: hoja tipo Excel con experiencia tipo Apple."
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Utilidades
  intl: 0.20.2
  collection: ^1.18.0

  # Navegación
  go_router: ^16.3.0

  # Estado / preferencias
  shared_preferences: ^2.3.2

  # Persistencia
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Syncfusion (alineadas)
  syncfusion_flutter_core: ^31.2.5
  syncfusion_flutter_datagrid: ^31.2.5
  syncfusion_flutter_xlsio: ^31.2.5

  # Archivos / exportación
  file_selector: ^1.0.4
  csv: ^6.0.0
  path: ^1.9.1
  path_provider: ^2.1.4

  # HTTP para backend CloudStore
  http: ^1.2.0

  # UX / animaciones
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  lottie: ^3.1.2
  url_launcher: ^6.3.2

  # Compartir / correo
  share_plus: ^12.0.1
  flutter_email_sender: ^8.0.0

  # Voz a texto
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1

  # GPS / ubicación
  geolocator: ^12.0.0

  # Diagnóstico (opcional)
  sentry_flutter: ^9.7.0
  package_info_plus: ^9.0.0

  # Autenticación Google
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/bitflow_logo.png
